services:
  db-users:
    container_name: db-users
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - db-pgdata-users:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-pgdata-users:

