name: e-commerce-shop
services:
  db-users:
    container_name: db-users
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - db-pgdata-users:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - e-commerce-shop

  db-inventory:
    container_name: db-inventory
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    volumes:
      - db-pgdata-inventory:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - e-commerce-shop

  db-reviews:
    container_name: db-reviews
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviews
    volumes:
      - db-pgdata-reviews:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - e-commerce-shop

  eureka-service:
    container_name: eureka-service
    build:
      context: ./eureka-service
    image: eureka-service
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    networks:
      - e-commerce-shop

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    image: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    depends_on:
      - eureka-service
    networks:
      - e-commerce-shop

  user-service:
    container_name: user-service
    build:
      context: ./user-service
    image: user-service
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    depends_on:
      - eureka-service
      - db-users
    networks:
      - e-commerce-shop

  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
    image: auth-service
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    depends_on:
      - eureka-service
    networks:
      - e-commerce-shop

  inventory-service:
    container_name: inventory-service
    build:
      context: ./inventory-service
    image: inventory-service
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    depends_on:
      - eureka-service
    networks:
      - e-commerce-shop

volumes:
  db-pgdata-users:
  db-pgdata-inventory:
  db-pgdata-reviews:

networks:
  e-commerce-shop:
    driver: bridge

