api:
  auth-service: lb://auth-service/api/v1/auth
server:
  port: 8080
spring:
  application:
    name: api-gateway
  profiles:
    active: dev
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/api-docs
      - name: inventory-service
        url: /inventory-service/api-docs
    path: /swagger
