name: e-commerce-store
services:
  db-users:
    container_name: db-users
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - db-pgdata-users:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - e-commerce-store

  db-inventory:
    container_name: db-inventory
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    volumes:
      - db-pgdata-inventory:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - e-commerce-store

  db-reviews:
    container_name: db-reviews
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviews
    volumes:
      - db-pgdata-reviews:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - e-commerce-store

  db-orders:
    container_name: db-orders
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    volumes:
      - db-pgdata-orders:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped
    networks:
      - e-commerce-store

  eureka-service:
    container_name: eureka-service
    image: 8160202/eureka-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    networks:
      - e-commerce-store

  api-gateway:
    container_name: api-gateway
    image: 8160202/api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    depends_on:
      - eureka-service
    networks:
      - e-commerce-store

  user-service:
    container_name: user-service
    image: 8160202/user-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    depends_on:
      - eureka-service
      - db-users
    networks:
      - e-commerce-store

  auth-service:
    container_name: auth-service
    image: 8160202/auth-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    depends_on:
      - eureka-service
    networks:
      - e-commerce-store

  inventory-service:
    container_name: inventory-service
    image: 8160202/inventory-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    depends_on:
      - eureka-service
    networks:
      - e-commerce-store

  order-service:
    container_name: order-service
    image: 8160202/order-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    depends_on:
      - eureka-service
    networks:
      - e-commerce-store

  reviews-service:
    container_name: reviews-service
    image: 8160202/reviews-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    restart: unless-stopped
    depends_on:
      - eureka-service
    networks:
      - e-commerce-store

volumes:
  db-pgdata-users:
  db-pgdata-inventory:
  db-pgdata-reviews:
  db-pgdata-orders:

networks:
  e-commerce-store:
    driver: bridge

