api:
  inventory-service: lb://inventory-service/api/v1/products
server:
  port: 8085
spring:
  application:
    name: order-service
  profiles:
    active: dev
springdoc:
  api-docs:
    path: /api-docs
