name: Docker Publish

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'database/**'
      - 'documentation/**'
      - 'README.md'
      - '.insomnium'
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [eureka-service, api-gateway, user-service, auth-service, inventory-service, reviews-service, order-service, notification-service]
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 8160202
          password: ${{ secrets.DOCKER_HUB_PW }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:${{ matrix.service }}"
          push: true
          tags: 8160202/${{ matrix.service }}:latest
          platforms: 'linux/arm64,linux/amd64'

